name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Committer and Repository Information
        id: commit_info
        run: |
          COMMITTER=$(git log -1 --pretty=format:'%an')
          REPO_NAME=$(basename -s .git $(git config --get remote.origin.url))
          echo "::set-output name=committer::$COMMITTER"
          echo "::set-output name=repo_name::$REPO_NAME"

      - name: Send Discord Webhook
        run: |
          COMMITTER="${{ steps.commit_info.outputs.committer }}"
          REPO_NAME="${{ steps.commit_info.outputs.repo_name }}"
          COMMIT_MESSAGE="${{ steps.commit_info.outputs.commit_message }}"
          MESSAGE="${COMMITTER} pushed a new commit to ${REPO_NAME}!\nCommit Message:\n\`\`\`${COMMIT_MESSAGE}\`\`\`"
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "'"$MESSAGE"'"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
