name: Full Python Linting

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Flake8 (Linting)
        run: |
          flake8 --max-line-length 100 --exclude=tests .
      - name: Run Black (Code Formatting Check)
        run: |
          black --check --exclude=tests .
      - name: Run isort (Import Sorting Check)
        run: |
          isort --check-only --diff --skip=tests .

      - name: Run isort (Import Sorting Check)
        run: |
          isort --check-only --diff .
